#!/bin/bash
alias 1='header "Without explicit typing"'
alias 2='header "Adding type annotations"'
alias 3='header "Runtime typing"'
alias 4='header "Third-party runtime typing"'
alias 5='header "Fast-API: Pydantic uService"'
alias 6='header "Typer: Pydantic CLI parsing"'
